### ISSUE TITLE
4.17.0 docs page is missing the search box

### ISSUE THREAD

**Issue by bughit** [lodash/lodash.com#107]
4.16.x had one

**Comment by jdalton** [comment]
Moved to #106.

**Comment by bughit** [comment]
> Our host has resolved an issue with one of their PoPs that didn't get the content flushed properly.

Are they saying it should be working now?  I am still getting a 404.

**Comment by jdalton** [comment]
@bughit What general area are you located? It might help them narrow things down.

**Comment by bughit** [comment]
MA
