### ISSUE TITLE
Search bar is gone from the 4.17.1 docs

### ISSUE THREAD

**Issue by natanavra** [lodash/lodash.com#108]
I used to use the 4.16.x docs, after refreshing I got the 4.17.1 docs and the search bar is not there.

Bug or removed on purpose?

**Comment by jdalton** [comment]
Hi @natanavra!

It's there for me. Try clearing your cache.

**Comment by natanavra** [comment]
Checked both Firefox and Chrome (latest) it's not there (doesn't show in the inspection tool as part of the DOM either)

**Comment by mklinga** [comment]
I'm getting the same behaviour on the docs, also the REPL seems missing.

On the console you can see that the the url: https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js) gives 404 and in the end the docs.js throws on `Fuse not defined`

print from the console:
```
https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js) Failed to load resource: the server responded with a status of 404 ()

4.17.2:1 GET https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js) 

docs.js:1 Uncaught ReferenceError: Fuse is not defined(…)(anonymous function) @ docs.js:1(anonymous function) @ docs.js:1
```

**Comment by jdalton** [comment]
@mklinga What browser & browser version are you in?

**Comment by mklinga** [comment]
Both firefox 49 & Chrome  54.0.2840.87 (64-bit), on macOS Sierra

**Comment by jdalton** [comment]
Cool. I've renamed the file.

**Comment by bughit** [comment]
This issue has already been reported (#106, #107), it would be much better for this to be tracked in one open, unlocked issue, than 3 closed ones (with one locked but still getting status updates)

Renaming the file does not resolve the problem.  It loads fine directly from cdn.jsdelivr.net, with or without the paren that you removed.

https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js
https://cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min).js

But lodash.com does not link to it directly, it goes through lodash.com

https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min.js

https://lodash.com/vendor/cdn.jsdelivr.net/g/fuse@2.5.0,immutable.js@3.8.1,react@15.3.2(react.min.js+react-dom.min).js

Both of these produce a 404.  This 404 is generated by your server,and should be visible in your logs.  It seems like you host should have enough info to figure this out, but you can bypass them by linking **directly** to cdn.jsdelivr.net.  Not sure there's even any benefit in having your server proxy this request.

**Comment by jdalton** [comment]
@bughit We use [netlify](https://www.netlify.com/) to host our static site. Two 404's is pretty odd.
