### ISSUE TITLE
firefox search box perf (input lag)

### ISSUE THREAD

**Issue by bughit** [lodash/lodash.com#109]
firefox 49.0.2 on ubuntu 14.04 x64

compared to chrome, there's a significant input lag in the searchbox making it almost unusable in firefox

**Comment by jdalton** [comment]
Hi @bughit!

I can't repro input lag on macOS Sierra or Win10.

Related to #45.

**Comment by simshaun** [comment]
Seeing the same thing here (though it's not necesarily unusable in Firefox, just slow).

Win10/Firefox57. Holding down backspace to clear out the search term. Typing "find" as fast as I can *after* I clear out the search term:
http://recordit.co/AvWhd2Pbel

Compare to Win10/Chrome:
http://recordit.co/Xn7NsLDTbU

In Firefox, it looks like it's getting bogged down in Layout, 
![image](https://user-images.githubusercontent.com/379519/32800665-face1da0-c948-11e7-9536-f255a57b699d.png)

![image](https://user-images.githubusercontent.com/379519/32800724-1e31afc8-c949-11e7-8ea5-d2d3dad77890.png)

![image](https://user-images.githubusercontent.com/379519/32800740-26bf4b32-c949-11e7-8a89-b3a2917b2dd3.png)

**Comment by jdalton** [comment]
Related to this Firefox bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1300939

**Comment by netgfx** [comment]
It happens of Chrome as well, after the alert box to `close` or `wait` out the scripts it unlocks
