### ISSUE TITLE
Switch + searchbox KO

### ISSUE THREAD

**Issue by euphocat** [lodash/lodash.com#112]
When accessing the doc page, the version switch is sometimes not working + the seach box is not displayed. I usuallly get this error when accessing the page with an anchor.

On chrome (ubuntu + windows 7) 
access https://lodash.com/docs/3.10.1#dropRight
do ctrl + shift + r

![image](https://cloud.githubusercontent.com/assets/1592057/20456346/6e5ef6da-ae75-11e6-8b52-195cc44bb286.png)

**Comment by jdalton** [comment]
Dup of #106.
