### ISSUE TITLE
Search bar should always be visible

### ISSUE THREAD

**Issue by atg** [lodash/lodash.com#113]
At the moment, the search bar is not always visible, rather it scrolls with the sidebar.

Which means if you scroll down the list scanning for something -- and don't find it -- you have to scroll all the way back up again to start a search. Or if you clicked on something at the bottom and then afterwards want to start a search for something else, you have to scroll the sidebar to the top.

So it would make more sense for the search bar to always be visible, regardless of how the sidebar has been scrolled.

There is a lot of free space in the main header where the search bar could live. Alternatively, it could be made fixed at the top of the sidebar.

**Comment by jdalton** [comment]
Hi @atg.

If you're up for making a PR that would be a rad addition.
