### ISSUE TITLE
Header and sidebar cause poor scrolling performance due to constant redraws

### ISSUE THREAD

**Issue by Soviut** [lodash/lodash.com#115]
The header and sidebar positioning cause them to redraw on every scroll frame.

![pasted_image_at_2016_11_30_12_22_am_720](https://cloud.githubusercontent.com/assets/226882/20740928/fa55310a-b694-11e6-9360-93c9d201fd11.png)

This can be solved by making them 3D layers that are GPU accelerated.

![pasted_image_at_2016_11_30_12_25_am_480](https://cloud.githubusercontent.com/assets/226882/20741011/7c7ff318-b695-11e6-88d1-b785e36e73c8.png)

**Comment by jdalton** [comment]
Hi @Soviut!

Unfortunately, it's not that simple. Dup of https://github.com/lodash/lodash.com/pull/41#issuecomment-247642803.
Even with redraws the scroll perf is fine-enough. I can zip it around even on mobile Safari.

**Comment by Soviut** [comment]
Strange that it would cause a crash. You could always use media queries to disable it on smaller screens.

**Comment by jdalton** [comment]
Are you up for creating a PR?

**Comment by Soviut** [comment]
Yes, I am.

**Comment by jdalton** [comment]
Cool, I'll accept it :D

**Comment by Soviut** [comment]
Great. Could we re-open the ticket so I have something to point the PR at when it's done?

**Comment by jdalton** [comment]
@Soviut Still up for it?
