### ISSUE TITLE
Documentation: Fuzzy search

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [lodash/lodash.com#123]
How about this: http://fusejs.io/

**Comment by jdalton** [comment]
Hi @bjorn-ali-goransson!

We're [using that](https://github.com/lodash/lodash.com/blob/d41b271136a2f0e5a2434d2784848bc297bc3bff/assets/js/docs.js#L24) :)

**Comment by bjorn-ali-goransson** [comment]
Nice! Although I really thought that it would do prefix searches as well. Like "faltt" does not match "flatten", but "flatt" does.

**Comment by jdalton** [comment]
It could be tweaking the threshold option (or other option a bit). If you tinker with it and get something working feel free to send a PR.
