### ISSUE TITLE
Version selection dropdown blocking searchbox in Safari 9

### ISSUE THREAD

**Issue by cheapsteak** [lodash/lodash.com#126]
Version 9.1.2 (11601.7.7)

![image](https://cloud.githubusercontent.com/assets/743976/22296397/048569cc-e2e8-11e6-8f71-91b29715c6e7.png)

![image](https://cloud.githubusercontent.com/assets/743976/22296424/1d00c474-e2e8-11e6-8bd8-c85e8d75f606.png)

**Comment by jdalton** [comment]
Moved to #127.
