### ISSUE TITLE
issue(s) with `_.sort()` method

### ISSUE THREAD

**Issue by ZuBB** [lodash/lodash.com#129]
Hi there!

there is neither entry (in left column) not documentation (in right panel) for `_.sort()` method. dev tools does not suggest it as a method then I type `_.sor...` in console. However..

In docs on `_.chain()` it is mentioned and in our code we user it as a part of chain and I am sure it works. AFAIK if method is available as chained version there should be also its "vanilla" version. I have checked change log and I did not find any bits on that.

I still missing whole picture but I do hope you should help us here 😃 

<img width="100%" src="https://cloud.githubusercontent.com/assets/597016/22477591/5c188cd0-e7ef-11e6-93f3-1db433813c88.png">

**Comment by jdalton** [comment]
Hi @ZuBB!

The handful of array methods have their own special call out just a bit above the section you highlighted
> The wrapper Array methods are:
```
concat, join, pop, push, shift, sort, splice, and unshift
```

**Comment by ZuBB** [comment]
Oh, I got it. Sorry for this invalid issue :(

**Comment by jdalton** [comment]
No worries 😸
