### ISSUE TITLE
Feature request: Reduce visual noise in docs

### ISSUE THREAD

**Issue by Loilo** [lodash/lodash.com#133]
Whenever I take a look at the docs I struggle to properly keep track of the list of methods. I came to the conclusion that this is probably due to the noise of the `_.` on the left of every method.

I think it'd be a lot more convenient to have those two characters a little bit faded out. I've done this locally with some JavaScript and it's way nicer for my eyes (40% opacity).

<img src=https://cloud.githubusercontent.com/assets/1922624/22977474/fc340050-f38e-11e6-9abf-0a95a769b93c.png width=80%>

What do you think?

**Comment by jdalton** [comment]
@Loilo I can dig it. Would you mind creating a PR?

**Comment by Loilo** [comment]
I'll see if I can wrap my head around it, shouldn't be too hard though. :)

**Comment by Loilo** [comment]
Mh. Okay, there's oneproblems with that: The CSS is inside this repo but the markup change is to be made in the lodash repo.

* Should I do one pull request in each?
* The lodash's master branch is pretty strange right now anyway, so it's probably best to just wait for v5 with this improvement?

**Comment by jdalton** [comment]
You can just manually change the doc html files in `lodash/lodash.com` for now. I'll port the modifications over when things get straightened up for v5.

**Comment by jdalton** [comment]
Moved to #134.
