### ISSUE TITLE
Some headers invisible

### ISSUE THREAD

**Issue by Semigradsky** [lodash/lodash.com#136]
https://lodash.com/docs/4.17.4#VERSION

https://lodash.com/docs/4.17.4#templateSettings

![image](https://cloud.githubusercontent.com/assets/1198848/23067658/66847554-f531-11e6-8b6b-f6dd992a1113.png)

Invisible code:
```html
<h3 id="VERSION">
    <a href="#VERSION" class="fa fa-link"></a>
    <a href="#VERSION"><code>_.VERSION</code></a>
</h3>
```

Normal code:
```html
<h3 id="templateSettings-escape">
    <a href="#templateSettings-escape" class="fa fa-link"></a>
    <code>_.templateSettings.escape</code>
</h3>
```

**Comment by jdalton** [comment]
Thanks @Semigradsky!
