### ISSUE TITLE
[RESPONSIVENESS] Loads of layout when resizing the page

### ISSUE THREAD

**Issue by motss** [lodash/lodash.com#138]
Just found out that the responsiveness is sluggish and feels terrible when resizing the page.
Timeline recording shows that the page spends most of the time doing layout during resizing.

<img width="1680" alt="screen shot 2017-03-29 at 10 42 09 am" src="https://cloud.githubusercontent.com/assets/10607759/24436628/2df40ba2-146f-11e7-856f-73d01fcac36c.png">

**Comment by jdalton** [comment]
Hi @motss!

If you've got a spare PR l'd dig it, but if not this is a known limitation.
