### ISSUE TITLE
2017 design touchups

### ISSUE THREAD

**Issue by veksen** [lodash/lodash.com#140]
Are we looking to renew the design for 2017?

If so, I have some ideas in mind. I could offer something we can discuss over.

Also, I'm thinking of adding some content, including:
- stats (npm/downloads)
- community (Gitter, etc?)

**Comment by jdalton** [comment]
Go for it!

**Comment by veksen** [comment]
First mockup, I didn't look or consider any content change, yet:

Noteworthy changes:
- Using system font, like Github, Medium, and others (see https://booking.design/implementing-system-fonts-on-booking-com-a-lesson-learned-bdc984df627f and https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/) (so, in this case, San Francisco on Mac/iOS, Segoe UI on Windows, and Roboto/Ubuntu on Linux)
- Dropping underlines for links, but using a much more distinctive color (I've yet to test for colorblind users, so still to reconsider)
- Oversized header, I can see how this can be controversial
- Dropping the shadowy content box

Another route I have in mind is a full-height header, with only the essential:
- Buttons to Docs + FP guide
- Large logo/headline
- Quick example
- Download links

I'm also considering a fixed menu, in case more sections are added.

Are we open to a subtle sidebar?

I haven't visited the docs yet, but I want to look at them as well. 

![lodash-2017](https://cloud.githubusercontent.com/assets/3461986/25073190/405c55f8-22af-11e7-840c-dc9545b2a71b.png)

**Comment by veksen** [comment]
Full page header:

Couldn't figure out how to add the example. If we want it, I can try something.

![Uploading lodash-2017-above-the-fold-cut.png…]()

**Comment by jdalton** [comment]
I like how the most useful links are front and center on the full page header. I'm not sure about the full gradient though but I'm keeping an open mind.

Lodash v5 will stress ECMAScript modules (ESM) and Node use so browser examples will be secondary.
The core build, full build, and custom builds will be reemphasized as well, leaving just the CDN link which can be reworded.

**Comment by veksen** [comment]
Could you expand "The core build, full build, and custom builds will be reemphasized as well, leaving just the CDN link which can be reworded."? Do you have an idea on how you want to bring those?

On the full gradient, I don't have a lot of ideas, but would like to stay away from a plain white/gray background. I'll try some stuff on my side.

**Comment by jdalton** [comment]
*Typo, that's **deemphasized*.

**Comment by veksen** [comment]
Trying to find some time this week.

**Comment by veksen** [comment]
Or this year :)

Color theme and docs touch ups.

![docs v1 dark](https://user-images.githubusercontent.com/3461986/28235910-758c5570-68e6-11e7-86c3-09edc3450b2d.png)

**Comment by veksen** [comment]
Along with an updated home page with the dark theme.

![website v2 above-the-fold dark](https://user-images.githubusercontent.com/3461986/28236453-14373b32-68f5-11e7-893c-48909743d223.png)

And a reverted version using the white theme, but the black header.

![website v2 above-the-fold dark - reversed](https://user-images.githubusercontent.com/3461986/28236506-c7ff274c-68f5-11e7-9cdd-ffb8cefd5a78.png)

**Comment by veksen** [comment]
@jdalton are we still open to the idea of a redesign with either a dark or a white theme? Do you have an opinion? If so, I'd explore a bit more and get feedback from other designer friends! I'd first go with a version that doesn't have behavioral changes, then we can explore behaviors later, if needed.

(I know most of your time is currently spent on esm atm, I can handle this one on my own pretty much, but I need some feedback :))

**Comment by jdalton** [comment]
@veksen I'm totally open to themes. I'm happy to give feedback when needed.

**Comment by aerori** [comment]
:3c
![image](https://user-images.githubusercontent.com/31824839/52891332-58e81a80-3158-11e9-9158-827ebde2a106.png)

**Comment by veksen** [comment]
I'm closing this in favor of #201.
