### ISSUE TITLE
Docs accessible as a subdomain

### ISSUE THREAD

**Issue by veksen** [lodash/lodash.com#141]
What about redirecting docs.lodash.com to lodash.com/docs? Is this even possible in the current setup?

**Comment by jdalton** [comment]
It's possible. Do you have a plan for the subdomain?

**Comment by jdalton** [comment]
Ping.

**Comment by veksen** [comment]
Sorry, I'm not sure if I understand your question?

**Comment by jdalton** [comment]
What will having docs on a sub domain enable for you?

**Comment by veksen** [comment]
It wasn't necessarily a request for me. I find myself typing docs.lodash.com, just to land on a 404. I just imagine I cannot be the only one. Not a priority for sure.
