### ISSUE TITLE
Carbon add covers sidebar

### ISSUE THREAD

**Issue by Lucretiel** [lodash/lodash.com#147]
The carbon ad in the lower-left corner of the screen covers the lodash index. I don't have a problem with the ad itself, but it means that when doing a Ctrl-F for lodash functions, sometimes the highlighted result is occluded by the ad. More generally, it means that when scrolling the sidebar, the function list mixes with the ad in an unsightly way. Please make the ad and the sidebar siblings, rather than have the former cover the latter.

**Comment by jdalton** [comment]
Hi @Lucretiel!

When scrolling all the way down the ad shouldn't cover the table of contents. If you're seeing something else feel free to send a PR.

**Comment by Lucretiel** [comment]
That's not the problem, though.

Here's a simple repro: Under the current (4.17.4) version of the site, in Chrome, scroll such that `lastIndexOf` is 2 or 3 elements above the Carbon ad. Then Ctrl-F for pull, and click through the results. Notice how the various `pull*` functions (`pullAll`, `pullAllBy`, `pullAllWith`, etc) are occluded by the ad, but still present on the page, and as a result you can't see the successful search hits in chrome.
