### ISSUE TITLE
The documentation page loading is blocked by runkit.com

### ISSUE THREAD

**Issue by Reinmar** [lodash/lodash.com#154]
<img src="https://user-images.githubusercontent.com/156149/28415269-37e68c14-6d4f-11e7-9922-c9467cd31609.png" width=50%>

I'm not sure what runkit.com is used for but it completely blocks the documentation. And now it seems to be done which makes the documentation inaccessible.

**Comment by jdalton** [comment]
Hi @Reinmar!

The issue looks to have resolved itself. I'll look into moving the script a bit lower (I believe I've done that before though).
