### ISSUE TITLE
_.get is missing from TOC

### ISSUE THREAD

**Issue by fehergeri13** [lodash/lodash.com#156]

**Comment by jdalton** [comment]
Hi @fehergeri13!

I see it:
<img width="310" src="https://user-images.githubusercontent.com/4303/29775299-888d9170-8bb9-11e7-9b1b-134f5c7ca813.png">

**Comment by fehergeri13** [comment]
Well, that is interesting. I am sure, I could not find it. I checked it multiple times. Maybe I should have created a screenshot.
