### ISSUE TITLE
_.thru() example: _.chain() is redundant there?

### ISSUE THREAD

**Issue by verheyenkoen** [lodash/lodash.com#159]
Is there any reason to have a chain step in the `_.thru()` [example](https://lodash.com/docs/4.17.4#thru)? I guess `_(...)` is already chaining the lot?

```
_('  abc  ')
 .chain()  // <-- this line here
 .trim()
 .thru(function(value) {
   return [value];
 })
 .value();
// => ['abc']
```

Source: https://github.com/lodash/lodash.com/blob/5a26bb4ce1f2d2be4e2a7805c1fef88eddd6680e/docs/4.17.4.html#L5134

**Comment by jdalton** [comment]
Hi @verheyenkoen!

Lodash has implicit chaining so it will terminate the chain for things like `trim` which return a primitive string unless you call `.chain()` which activates explicit chaining.

**Comment by verheyenkoen** [comment]
I see, thanks for explaining.
