### ISSUE TITLE
Docs conversion for escapeRegExp method.

### ISSUE THREAD

**Issue by falsyvalues** [lodash/lodash.com#160]
This issue was found in this pull request [3448](https://github.com/lodash/lodash/pull/3448). During conversion of a jsdocs of `escapeRegExp` to website version we are losing backslash in `"\"`.

**Comment by jdalton** [comment]
Thanks for the heads up!

**Comment by yejiajiehz** [comment]
same problem with latest 4.17.11
![image](https://user-images.githubusercontent.com/1755967/59660157-67b00e00-91da-11e9-842f-1e9f3ff6459f.png)

https://lodash.com/docs/4.17.11#escapeRegExp
