### ISSUE TITLE
Docs: improve navigation ux, clickable headers

### ISSUE THREAD

**Issue by falsyvalues** [lodash/lodash.com#165]
Since I stopped playing FPS games my accuracy is getting low :monkey_face:  would be superb nice to have this feature:
Make grouping headers clickable on side menu, not only these small icons (:heavy_plus_sign:)  :heart_eyes:. 

![capture](https://user-images.githubusercontent.com/1199350/33758198-99f5d87a-dbfd-11e7-933c-fa139c89291b.PNG)

**Comment by veksen** [comment]
Hiya @falsyvalues, legit point! 

@jdalton I have some free time this week, so I could tackle this. Unless @falsyvalues feels like throwing in a PR!

**Comment by jdalton** [comment]
Thanks @falsyvalues for the suggestion and @veksen for the PR offer!

**Comment by falsyvalues** [comment]
@veksen I remember that you were planning some site redesign, so its up to you. If there is no ETA for this I can handle this :100:.

**Comment by ellessuom** [comment]
I found this was still open. 
Please, let me know if the way I done it is not what you were looking for!

Have a nice day!

**Comment by jdalton** [comment]
Moved to #184

**Comment by falsyvalues** [comment]
🍾
