### ISSUE TITLE
Error: Cannot find module 'lodash@4.17.4'

### ISSUE THREAD

**Issue by kreedz** [lodash/lodash.com#168]
![2512-lodash-site-error](https://user-images.githubusercontent.com/2128965/34340509-d22538ba-e9a6-11e7-9a8b-6c8a39ef1d97.png)

**Comment by jdalton** [comment]
Looks like a hiccup in the third party service. There is nothing actionable on our side

**Comment by jdalton** [comment]
RunKit has resolved the issue. They had a build glitch with Node 9.
