### ISSUE TITLE
Unresponsive "embed.runkit.com" disable documentation

### ISSUE THREAD

**Issue by eugeny-dementev** [lodash/lodash.com#186]
For some reason i have problem with access to embed.runkit.com and until it reach it's response timeout (and this is always more than minute) documentation is not usable.
![image](https://user-images.githubusercontent.com/9016345/40897869-1e64930c-67f0-11e8-9556-7770bee0e38b.png)

**Comment by jdalton** [comment]
Thanks @eugeny-dementev!

It's probably just a temporary hiccup. Let me know if it persists days and days.

**Comment by eugeny-dementev** [comment]
It is already happen more than a week. So i just need to open devtools every time to block that domain to work with docs. In first i want to open PR with making that domain loading in async but page is generating from some config and i'm not sure that this config support "async" option.

**Comment by jdalton** [comment]
Ah okay. I've updated the site to make its script async. It may take a couple of refreshes on your end.
