### ISSUE TITLE
re-enable cmd+f, have to wait too long to find

### ISSUE THREAD

**Issue by JulianKingman** [lodash/lodash.com#187]
The documentation page swallows up the `cmd + f` command, which doesn't allow me to search before it finishes completely loading, which is usually another few seconds. I think it takes a long time because the searchNode ref needs to resolve.

The code in question would be here: https://github.com/lodash/lodash.com/blob/14cf2780ff9c70e1ec6f78baf19a60523655c9cc/assets/js/docs.js#L228

I think disabling it would be the nicest user experience, but maybe it could be fixed instead.

**Comment by jdalton** [comment]
Hi @JulianKingman!

I'll see what I can do.

**Comment by jdalton** [comment]
It looks like I'm only preventing the default behavior for the tab and `/` character so it shouldn't be swallowing `cmd+f`.
