### ISSUE TITLE
Browser locks while loading Lodash docs

### ISSUE THREAD

**Issue by bbottema** [lodash/lodash.com#188]
Reopening #45, since that one was closed and locked for reasons beyond me. Pretending the problem isn't there doesn't magically make it go away.

> jdalton added the wontfix  label on Sep 2, 2016
> jdalton commented on Sep 2, 2016
> If you come up with anything let me know.
> **For now it's just one of those things I hope gets better with time.**

It's clear this issue is not going away since people have been reporting it regularly since 2016.

> I've visited the docs in Chrome plenty of times and have never had a problem. I checked with Firefox 60.0.2 and it loads quick too.

If you want to close it because you're not interested, find it unimportant or simply like a clean bugs tab, then by all means go ahead, but closing and locking it because you don't get enough "actionable feedback" and hope it goes away saying It Works On My Machine... well...

Now I was going to see if I can dig up some more info, but Chrome's performance profiler simply doesn't finish loading. I have no issue with 2.4.2. 3.10.1 does have a delay, but isn't nearly as problematic as 4.17.10. Seems to be related to the amount of content. (sidenote: the complete content always being shown is problematic from an UX perspective, considering I'm unable to scroll up or down without skipping 3 complete sections (I'm on touchpad) ).

To be clear, here's what I actually see: the page loads fine, the search input even takes a few characters but then the page locks up completely. This happens whether I use the input or not.

Tried in incognito mode and actually have no issues at all there. I'm now suspecting an add-on is causing or triggering the delay. After re-enabling my add-ons one-by-one, I found Evernote Web Clipper to be the cause or trigger for the chain of delay. I have no idea how or why, I don't see anything in Chrome indicating Evernote is doing anything, but when I disable it the problem goes away. I haven't had this issue on any other website until now in the past 3 years.

I can't speak for the other issue reporters tough. I rather not have to disable Evernote Web Clipper on just your documentation tough. At least I have a workaround now.

**Comment by jdalton** [comment]
Hi @bbottema!

Thanks for opening the issue. I get that you're frustrated so I've given you a cool-off period for Lodash projects. During that time you'll not be able to open issues, PRs, comment, or interact with the projects. 

While I would love to make the site work for everyone without a clear repro case _(that I can see and debug)_ I cannot resolve the issue which is why it may get resolved as `invalid`. It simply means I can't fix it because I can reproduce the issue. If you can and can also provide a patch that's fantastic and I'll happily take a PR.
