### ISSUE TITLE
Location requested

### ISSUE THREAD

**Issue by pillowfication** [lodash/lodash.com#200]
![screen shot 2019-02-15 at 14 38 56](https://user-images.githubusercontent.com/7277535/52889869-c71be580-3136-11e9-8036-c3abee9561f8.png)

Sometimes when visiting lodash.com on Chrome, I get a request for my location.

**Comment by jdalton** [comment]
Hi @pillowfication!

Maybe our google analytics is overreaching? 
I'm not sure. Feel free to give our source review though.
