### ISSUE TITLE
Better example for method chaining

### ISSUE THREAD

**Issue by elias6** [lodash/lodash.com#208]
I really like using lodash method chaining to create concise and powerful pipelines, but every time I use it, the people at my work complain that they have trouble understanding my code.

I think it can be made more understandable with a simple example, which uses it as it is typically used, and does not combine it with other lodash features that people may be unfamiliar with. Maybe something like this:

```javascript
var numbers = [1, 2, 3, 4, 5];

var newNumbers = _(numbers)
    .map(x => 2 * x)
    .filter(x => x < 7)
    .value();
// => [2, 4, 6]
```

**Comment by jdalton** [comment]
Hi @elias6!

I believe our docs cover some chaining examples. It may help your coworkers if they see the array of `numbers` as being wrapped in a sequence membrane that allows queuing a operations to perform on `numbers`.

**Comment by elias6** [comment]
Why was this closed? Some smart people that I work with have trouble understanding chaining, so I don't think it is unreasonable to suggest that the documentation could be improved.

I would guess that in most cases where method chaining is used, people don't really care about the intermediate values, and chain one method after another. For that reason, it may be useful to show an actual example of that being done, not necessarily in place of the existing example, but maybe in addition to it.

I really think lodash chaining is a powerful and useful tool that makes things easier and simpler, and I would like to be able to use it without my coworkers joking about having to read half the dictionary to understand my code.

**Comment by veksen** [comment]
If I may add, this Twitter thread illustrates a bit better how issues are managed

https://twitter.com/samselikoff/status/991395669016436736?s=21
