### ISSUE TITLE
Ad appears to (but doesn't) cover content in the left nav, mainly because of scroll bar indicator position

### ISSUE THREAD

**Issue by mmarvick** [lodash/lodash.com#209]
When I scroll through the left nav in the documentation, I got tricked into thinking the ad was covering some content that can't be scrolled to. It turned out not to be the case, but I took screenshot of the issues causing confusion below. These issues could probably all be solved by the solution brought up in #147 (making the sidebar and the ad siblings).

Screenshots are from Firefox 67.0.2 on Mac OS 10.14.5, but the behavior is the same in Chrome 75.0.3770.80.

### Scroll bar position

The scroll bar goes past the bottom of the list items, aligning to the bottom of the ad. This makes it feel like the scrollable content probably goes to the bottom of the ad as well.
<br />
<img width="308" alt="Screen Shot 2019-06-15 at 10 23 11 AM" src="https://user-images.githubusercontent.com/3861298/59554441-b1d58d00-8f57-11e9-8f65-0e247aacae84.png">
<br />
<img width="309" alt="Screen Shot 2019-06-15 at 10 23 17 AM" src="https://user-images.githubusercontent.com/3861298/59554442-b26e2380-8f57-11e9-9267-9a995ecc347c.png">
<br />
<img width="310" alt="Screen Shot 2019-06-15 at 10 14 38 AM" src="https://user-images.githubusercontent.com/3861298/59554382-d5e49e80-8f56-11e9-839b-25f272cf1eff.png">

### No separation
Visible in the last image above - when you get to the bottom of the list, there's nothing separating the list content from the ad, so it feels like there might be more. A horizontal rule might fix this. But if the scroll bar wasn't going past the content, tweaking this might not be necessary.

### `_.` renders over the ad content

You can see the `_.` (but not the method name itself) rendering on top of the ad. This gives the allusion that more stuff might be hiding down there.

<img width="263" alt="Screen Shot 2019-06-15 at 10 28 53 AM" src="https://user-images.githubusercontent.com/3861298/59554484-6a033580-8f58-11e9-88e7-a2f100a5ea84.png">
<br />
<img width="143" alt="Screen Shot 2019-06-15 at 10 16 47 AM" src="https://user-images.githubusercontent.com/3861298/59554379-c82f1900-8f56-11e9-824c-6cd4b0acd7a1.png">

**Comment by jdalton** [comment]
This is by design though if you can fix it I’d except a PR.
