### ISSUE TITLE
Search lagging? ~3fps

### ISSUE THREAD

**Issue by imcotton** [lodash/lodash.com#210]
Just noticed this pref issue today, I didn't tracking closely to the site updates, any idea on why and when?

**Comment by jdalton** [comment]
Hi @imcotton!

There have been no site updates.

**Comment by imcotton** [comment]
Odd, this is glance of flame chart by typing a few letters just now:

![Screen Shot 2019-07-06 at 13 46 46 PM](https://user-images.githubusercontent.com/149541/60752199-5a29bf00-9ff5-11e9-9525-6b211286bd15.png)

- Google Chrome 75.0.3770.100
- Mac OS 10.12.6

**Comment by imcotton** [comment]
@jdalton would you checkout the snapshot on above please, thanks.

**Comment by veksen** [comment]
Hello @imcotton! We are currently working on a new documentation (see #201). Given the way the current docs are built, debugging/profiling this might not be trivial, and I'd personally rather invest my time/energy into the next docs.
