### ISSUE TITLE
Build version on doc

### ISSUE THREAD

**Issue by MathRobin** [lodash/lodash.com#211]
Hi !

Could it be possible to add on each method on doc site if the method is included in core build or in full build please ?

Thanks in advance !

And many thanks for this great and useful tool !

Deduplicated from https://github.com/lodash/lodash/issues/4369

**Comment by jdalton** [comment]
Hi @MathRobin!

It's a good suggestion but I'm not carrying over the core build to the next major release of Lodash and instead will focus on the bundle-ability of modules (so folks can create their own core bundles).

**Comment by MathRobin** [comment]
Ah ok. That's good too !

**Comment by MathRobin** [comment]
Many thanks !
