### ISSUE TITLE
Search Box is Painfully Slow to Respond to Input

### ISSUE THREAD

**Issue by AaronBeaudoin** [lodash/lodash.com#212]
When using the search bar near the top of the left side, any typing takes about a second to show up and affect the list of functions.

I went to the reworked site and it seems the issue is fixed, but I do feel that this is a important usability problem and should be fixed on the live site as soon as possible.

I'm using Chrome 75.0.3770.142 on Windows 10.

**Comment by jdalton** [comment]
Hi @AaronBeaudoin!

Thanks for the report! This issue is intermittent and inconsistent across users. Since it's resolved in the redesign I'll let it shake out there.

**Comment by epixian** [comment]
still seems to be an issue.  Chrome 80.0.3987.132, Windows 10
