### ISSUE TITLE
Mashed up "Min, Max and Close" buttons in the PWA

### ISSUE THREAD

**Issue by OAyomide** [lodash/lodash.com#216]
I just installed the lodash PWA on linux (I use brave) and the minimize, maximize and close buttons are mashed up such that the minimize button does not even work as it seems not clickable.

Operating System: Ubuntu 18.04

See screenshot attached below
![loashsmashedup](https://user-images.githubusercontent.com/26779597/69799265-3d279f80-11d3-11ea-8d5a-22ec819ebd46.png)

**Comment by bnjmnt4n** [comment]
Given that the PWA is handled by your browser, this seems to be an issue with your browser's PWA handling/interaction with the desktop environment/window manager.
