### ISSUE TITLE
Width issue with social media division

### ISSUE THREAD

**Issue by saikiransathpadi** [lodash/lodash.com#269]
Social media division is distorted because of the width issue and some data is not visible too

![image](https://user-images.githubusercontent.com/56450993/210859624-690bbe1d-8d1f-47f5-b731-438d6b729770.png)

this is a duplicate of the issue raised in lodash js repo https://github.com/lodash/lodash/issues/5542

Fix: need to change the widths of respective elements

I have done the changes and will raise the PR.

**Comment by saikiransathpadi** [comment]
https://github.com/lodash/lodash.com/pull/270
Please have a look at the PR.

**Comment by jdalton** [comment]
Fixed by #270. Thank you @saikiransathpadi!
