### ISSUE TITLE
Rapid link rot.

### ISSUE THREAD

**Issue by Y-Less** [lodash/lodash.com#94]
I had previously been to this link:

https://lodash.com/docs

Which loaded a page fine, and I bookmarked the result for future reference.  Unfortunately, this was during 4.16.2 and so because of the redirect this was the page bookmarked:

https://lodash.com/docs/4.16.2

That worked fine until very recently when the minor version was bumped and the old page was deleted without even a note or redirect to:

https://lodash.com/docs/4.16.4

Not very helpful when your bookmarks suddenly stop working, especially when the initial redirect was what led me to that page for marking in the first place.

**Comment by jdalton** [comment]
This is by design. The links redirect, so no rot.
I do not want to carry around 32 v4 releases. It makes offline caching super heavy too.

If it helps you can just reference https://lodash.com/docs/4.

**Comment by Y-Less** [comment]
My point was they don't redirect.  Going to https://lodash.com/docs/4.16.2 just gives a 404 wheras it previously gave documentation.

**Comment by jdalton** [comment]
I can't repro that. You might try clearing your cache (maybe even clearing your application tab cache).

**Comment by phated** [comment]
Cache cleared and was able to reproduce.

**Comment by jdalton** [comment]
Hmm interesting. It appears most redirects work but without a service worker (so non Chrome/Firefox) the https://lodash.com/docs/4.16.2 link will 404.

**Comment by jdalton** [comment]
Patched https://github.com/lodash/lodash.com/commit/dd3a64619c7e98b8d952be0b6b2d837d62beb5aa.
